### ISSUE TITLE
Is access token a required parameter?

### ISSUE THREAD

**Issue by 5j9** [jayvdb/travis_log_fetch#13]
I couldn't make it work:
```
$ travis_log_fetch jayvdb/travis_log_fetch:90471373
Traceback (most recent call last):
  File ".../python3.6/site-packages/travispy/_helpers.py", line 19, in get_response_contents
    contents = response.json()
  File ".../python3.6/site-packages/requests/models.py", line 858, in json
    self.content.decode(encoding), **kwargs
  File ".../python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File ".../python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File ".../python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../.python/ve360/bin/travis_log_fetch", line 11, in <module>
    load_entry_point('travis-log-fetch==0.1.1', 'console_scripts', 'travis_log_fetch')()
  File ".../python3.6/site-packages/travis_log_fetch/cmdline.py", line 49, in main
    user = t.user()
  File ".../python3.6/site-packages/travispy/travispy.py", line 280, in user
    return User.find_one(self._session, '')
  File ".../python3.6/site-packages/travispy/entities/_entity.py", line 90, in find_one
    contents = get_response_contents(response)
  File ".../python3.6/site-packages/travispy/_helpers.py", line 34, in get_response_contents
    raise TravisError(contents)
travispy.errors.TravisError: [401] no access token supplied

```

**Comment by 5j9** [comment]
Well, it seems to work after passing access token, but it's odd that this option is listed under "optional arguments" section.
For others that may have this issue: Follow the instructions at http://travispy.readthedocs.io/en/latest/getting_started/#getting-started to acquire access token.
