### ISSUE TITLE
PyPy support

### ISSUE THREAD

**Issue by jayvdb** [jayvdb/travis_log_fetch#4]
Using tox with pypy and pypy3 results in the environment being dumped out in travis, including secrets, so a different style of `.travis.yml` is needed.

However, the builds for both errored because https://github.com/sigmavirus24/github3.py wanted `cryptography`, and `cryptography` failed.

**Comment by jayvdb** [comment]
```
$ pip install -r requirements.txt

You are using pip version 6.0.7, however version 7.1.2 is available.

You should consider upgrading via the 'pip install --upgrade pip' command.

Collecting travispy (from -r requirements.txt (line 1))

  Downloading TravisPy-0.3.3.zip

Collecting github3.py>=1.0.0a1 (from -r requirements.txt (line 2))

  Downloading github3.py-1.0.0a2-py2.py3-none-any.whl (107kB)

    100% |################################| 110kB 3.4MB/s 

Collecting python-dateutil (from -r requirements.txt (line 3))

  Downloading python_dateutil-2.4.2-py2.py3-none-any.whl (188kB)

    100% |################################| 192kB 2.1MB/s 

Collecting parse (from -r requirements.txt (line 4))

  Downloading parse-1.6.6-py2-none-any.whl

Collecting ConfigArgParse (from -r requirements.txt (line 5))

  Downloading ConfigArgParse-0.10.0.tar.gz

Collecting requests<3,>=2.2.1 (from travispy->-r requirements.txt (line 1))

  Downloading requests-2.8.1-py2.py3-none-any.whl (497kB)

    100% |################################| 499kB 889kB/s 

Collecting pyOpenSSL (from github3.py>=1.0.0a1->-r requirements.txt (line 2))

  Downloading pyOpenSSL-0.15.1-py2.py3-none-any.whl (102kB)

    100% |################################| 106kB 4.0MB/s 

Collecting ndg-httpsclient (from github3.py>=1.0.0a1->-r requirements.txt (line 2))

  Downloading ndg_httpsclient-0.4.0.tar.gz

Collecting pyasn1 (from github3.py>=1.0.0a1->-r requirements.txt (line 2))

  Downloading pyasn1-0.1.9-py2.py3-none-any.whl

Collecting uritemplate.py>=0.2.0 (from github3.py>=1.0.0a1->-r requirements.txt (line 2))

  Downloading uritemplate.py-0.3.0.tar.gz

Collecting six>=1.5 (from python-dateutil->-r requirements.txt (line 3))

  Downloading six-1.10.0-py2.py3-none-any.whl

Collecting cryptography>=0.7 (from pyOpenSSL->github3.py>=1.0.0a1->-r requirements.txt (line 2))

  Downloading cryptography-1.1.tar.gz (348kB)

    100% |################################| 352kB 1.4MB/s 

    Traceback (most recent call last):

      File "app_main.py", line 75, in run_toplevel

      File "app_main.py", line 581, in run_it

      File "<string>", line 20, in <module>

      File "/tmp/pip-build-77Tb4l/cryptography/setup.py", line 53, in <module>

        "cryptography 1.0 is not compatible with PyPy < 2.6. Please "

    RuntimeError: cryptography 1.0 is not compatible with PyPy < 2.6. Please upgrade PyPy to use this library.

    Complete output from command python setup.py egg_info:

    Traceback (most recent call last):



      File "app_main.py", line 75, in run_toplevel



      File "app_main.py", line 581, in run_it



      File "<string>", line 20, in <module>



      File "/tmp/pip-build-77Tb4l/cryptography/setup.py", line 53, in <module>



        "cryptography 1.0 is not compatible with PyPy < 2.6. Please "



    RuntimeError: cryptography 1.0 is not compatible with PyPy < 2.6. Please upgrade PyPy to use this library.
```
